version: 2
updates:
  - package-ecosystem: npm
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: github-actions
    target-branch: develop
    directory: /
    schedule:
      interval: monthly
