name: Test and Release
on:
  push:
    branches:
      - master
      - alpha

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
        with:
          # fetch all history
          fetch-depth: 0

      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16
          cache: npm

      - run: npx npm@8.7.0 ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx npx semantic-release
