name: Build, Lint and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  build-test:
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@269a893f6432649083afd1c3c6350793e8c00e4b
