name: Build, Lint and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  build-test:
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@118c76c1845aa9c8974dd0664742f4c46ed25304
